# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Title')),
                ('description', models.TextField(verbose_name='Short text')),
                ('content', models.TextField(verbose_name='Text')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2016, 11, 29, 23, 9, 42, 664164), verbose_name='Public date')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
                'ordering': ['-posted'],
            },
        ),
    ]
